### ISSUE TITLE
Trees stay after gathering node is destroyed

### ISSUE THREAD

**Issue by Cablefish1** [zunath/Freescape_JVM#26]
Actually i think it would be fine to just make the the tree objects themselves be the object you bash and destroy. The effects are all there and it makes it easier to build the module when you can actually see the object you're working with. I know you've experience playerwhining but it works on many servers :)

**Comment by zunath** [comment]
My main problems with trees are two-fold:

1.) The targeting area is huge. Trying to select NPCs next to a tree is almost impossible in certain scenarios. If identification is an issue, maybe we can put some sort of "sparkling lights" or something to that effect to indicate they're useable? We could also look at using the slightly larger Invisible Object placeable appearance.

2.) We shouldn't be placing down trees individually - we have NESS for that. Even if we don't want them to respawn for some reason, we should use it because it means it's a lot easier to update the objects later on. For example, if we need to change the level of the tree we just change it in the palette and all spawn points update automatically. If we hand place them we have to update instances across all areas which, in a large module, can take a really long time.

**Comment by Cablefish1** [comment]
Your're right on bot accounts. I don't think sparkling lights are necessary since they they work fine the way they are.

So it's mainly that the tree object that needs to "DestroyObject GetNearestObjectByTag tree_prop" right?

**Comment by zunath** [comment]
Sort of - they're attached by local objects so when the invisible object gets destroyed, it also destroys the prop. Basically accomplishes the same thing though.

So is there an action needed on this one or are we good with using NESS to spawn?
