### ISSUE TITLE
Faster way to eat food

### ISSUE THREAD

**Issue by Cablefish1** [zunath/Freescape_JVM#76]
I'm thinking the Rest menu could have an "eat food" subcategory. In here players can consume individual food items or ALL of a specific food item at once. This should help out a lot to make the hunger aspect more bearable for players.

**Comment by zunath** [comment]
When I can skip the activation event (which is coming soon) it'll just be a matter of players double clicking items to eat. I don't know if the act of eating is a problem so much as the amount of recovery from eating being too low. 

The main reason I don't want to put a rest menu option in for this is because it's difficult to intelligently pick the "right" food. If we end up having a way to customize individual food items - say, with increased recovery or a stat bonus or something - we might pick up a food item the player doesn't want. I think we should leave it to the player to decide which food they intentionally want to eat.

**Comment by zunath** [comment]
Consolidating this ticket down. Will track this in #45
